app/src/main/java/org/ea/sqrl/activites/identity/ExportOptionsActivity.java

Issue:
#209  
Description:
Added a check to see if the directory exists.  Only throw the error if, after we try to created it, the directory still doesn't exist.
Changes:
ExportOptionsActivity.java

Correct error dialog on second run of saving identity.

---

app/src/main/res/layout/activity_settings.xml

SettingsActivity does not conform to Android UI design guidelines. Save is supposed to be on the right and cancel on the left.
Description:
Switches the buttons around.

Switch button places in SettingsActivity

---

app/src/main/java/org/ea/sqrl/processors/SQRLStorage.java
app/src/main/java/org/ea/sqrl/services/IdentityPrintDocumentAdapter.java
app/src/main/java/org/ea/sqrl/utils/Utils.java

Issue #265
Description:
Earlier, I had observed that if the fields of the storage object were refreshed from the database before printing the identity PDF, then the verify block was of proper length, whereas if this read was not done, the error of the issue (longer than expected verify block) was printed.
I examined both `IdentityPrintDocumentAdapter` and also `ShowIdentityActivity`.  The latter activity appeared to already be refreshing the storage object from the database before use, so no changes appear to be required for that activity.  Those two places are where the problem `getVerifyingRecoveryBlock()` is being used in a new install / new identity situation that the issue describes.
Changes:
Added a method that refreshes the content of the storage object from the database and uses …

Added refreshStorageFromDb and used it before printing identity

---

app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java
app/src/main/java/org/ea/sqrl/activites/base/LoginBaseActivity.java

Issue #263
Description:
New method signatures that include a runnable for BaseActivity 
Changes:
Pass a runnable into the `showErrorMessage` method so that the next action is shown *after* the user sees the dialog.

Prevent next action from covering error

---

app/src/main/java/org/ea/sqrl/activites/create/NewIdentityDoneActivity.java

Issue #280 .
Description:
When you created your first identity and press back you should close app. 
Today you can go back to the introduction screen. Should not be available when identity is present.
Changes:
Close current activity and all other running activities and then fire up the simplified view so we end up in the same state as when you open the app with identities loaded.

Fix bug where the creating process goes to the wrong activity.

---

app/src/main/res/layout/fragment_login.xml

Issue #291
Description:
Removed fixed height.
Changes:
Removed fixed height in logon layout popup.  The problem was that the user had configured the OS to use largest fonts.

Remove fixed height in login popup

---

app/src/main/java/org/ea/sqrl/activites/CPSMissingActivity.java
app/src/main/java/org/ea/sqrl/activites/SimplifiedActivity.java
app/src/main/java/org/ea/sqrl/activites/UrlLoginActivity.java

Issue #272.
Description:
When a user logs in and a network or server error occurs the users quickpass is cleared.
Changes:
Don't clear quickpass when network or server error occurs.

Don't delete quickpass on network errors.

---

app/src/main/java/org/ea/sqrl/activites/identity/ChangePasswordActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ResetPasswordActivity.java
app/src/main/res/layout/activity_change_password.xml
app/src/main/res/layout/activity_reset_password.xml

Issue #278 (follow-up PR).
Description:
Deploy password strength meter to ChangePasswordActivity and ResetPasswordActivity.
Notes:
In ResetPasswordActivity, I hide the descriptive text at the top as soon as the password field gets focus, in order to gain some screen real estate. Otherwise, the strength meter is being concealed by the soft keyboard on smaller resolutions. I have tried different things to mitigate this, but found this to be the best solution overall. If anyone has a better idea, I'd be more than happy to hear about it. Thanks!

Deploy password strength meter

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/account/EnableAccountActivity.java
app/src/main/java/org/ea/sqrl/activites/account/RemoveAccountActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RekeyVerifyActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeEnterActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeShowActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ResetPasswordActivity.java
app/src/main/java/org/ea/sqrl/utils/RescueCodeInputHelper.java
app/src/main/res/layout-land/activity_rescuecode_show.xml
app/src/main/res/layout/activity_enable_account.xml
app/src/main/res/layout/activity_rekey_verify.xml
app/src/main/res/layout/activity_remove_account.xml
app/src/main/res/layout/activity_rescuecode_enter.xml
app/src/main/res/layout/activity_rescuecode_show.xml
app/src/main/res/layout/activity_reset_password.xml
app/src/main/res/layout/rescue_code_input.xml
app/src/main/res/values/strings.xml

Issue #298 .
Description:
Removed duplicate layout code and replaced it with only one import file: *rescue_code_input.xml*
Also added a helper class for dealing with input verification. The code of the affected activities was also refactored to use the this new helper class. All the logic is now in one place.
The following activities (layout and code) were affected:
```
activity_enable_account.xml
activity_rekey_verify.xml
activity_remove_account.xml
activity_rescuecode_show.xml
activity_rescuecode_enter.xml
activity_reset_password.xml
```
Changes/improvements:
- Removed duplicate layout code
- Removed duplicate verification code
- Removed error popups in favour of on-the-fly form input checks. Also, the "next"-button is now enabled/disabled on the fly for most of the activities.
- Focus …

Consolidate rescue code layout and code

---

app/src/main/java/org/ea/sqrl/activites/account/DisableAccountActivity.java
app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java
app/src/main/java/org/ea/sqrl/activites/base/LoginBaseActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ChangePasswordActivity.java

Issue #302.
Description:
Quickpass notification is shown in the notification bar and enables the removal of quickpass from the phone to increase security. This feature should be removed because it's confusing to users.
Changes:
Starting the background job for the delayed clearing of the QuickPass was decoupled from showing the notification. Finally, all calls to `showClearNotification()` were replaced with `clearQuickPassDelayed()`.
`showClearNotification()` was left in, maybe we'll decide to offer the functionality to power users later.

Remove quickpass notification

---

app/src/main/res/layout/activity_settings.xml

Issue #221.
Description:
Lastpass was triggered by the following InputText field in the settings activity:
```
<EditText
android:id="@+id/txtSettingsPasswordVerifyInSeconds"
...
```
Changes:
Added `android:importantForAutofill="no"` to the TextInput fields in the settings activity.
This just works on API 26+ but it sucessfully prevents Lastpass from popping up for me.

Fix: Lastpass is triggered by settings window

---

app/src/main/java/org/ea/sqrl/activites/IntroductionActivity.java
app/src/main/java/org/ea/sqrl/activites/LanguageActivity.java
app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java
app/src/main/java/org/ea/sqrl/activites/base/CommonBaseActivity.java
app/src/main/java/org/ea/sqrl/activites/create/CreateIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/create/EntropyGatherActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RekeyIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeEnterActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeShowActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ClearIdentityActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java

Issues #310, #218.
Description:
This should fix the "*language only partly updating*" as well as the "*language of activity title not updating*" bugs.
Changes:
Moved language update and activity title update code to `onCreate()` and added code to detect language changes in `onResume()`. If a language change is detected, the activity gets recreated, which ensures proper loading of all language assets. 
Added `CommonBaseActivity` that *EVERY* other activity inherits from (either directly or indirectly) and put the language update and language change detection code there. This way, every activity gets this functionality "for free" without dupliacting any code. This class could come in handy later as well if we need more common code.
As discussed in issue #310, we might consider refactoring …

Language change fix

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java
app/src/main/res/layout-land/activity_import.xml
app/src/main/res/layout/activity_import.xml
app/src/main/res/values/strings.xml

Issue #260.
Description:
Enable .sqrl identity file import by choosing the SQRL app in the "*open with app*" android dialog after tapping on a .sqrl file in downloads or a file explorer app.
Changes:
Register an intent filter in the manifest for `ImportActivity` to receive file `VIEW` intents for the mime types `text/*` and `application/*`. Detect such an intent in `onCreate()` and handle it the same way as the QR import would. In case of an invalid file, all buttons are disabled and an error message is displayed in the activity's description TextView.
I guess we'll see how this works on different APIs/devices, since there apparently were a lot of changes in this particular Android API over time and it's a BIG MESS!! Maybe we'll have to broaden the mime types in the future.

Handle .sqrl file intent

---

app/src/main/java/org/ea/sqrl/activites/SimplifiedActivity.java
app/src/main/java/org/ea/sqrl/activites/base/LoginBaseActivity.java
app/src/main/java/org/ea/sqrl/database/IdentityDBHelper.java
app/src/main/res/layout/activity_simplified.xml

Issue #220 .
Description:
Displays the currently selected identity name in the `SimplifiedActivity`, but only if more than one identity is present. Tapping on the identity name will open the screen where one can change the currently active identity. Overlong identity names will be truncated.
Please note that there is already a PR pending regarding this topic, but it was not updated in over two months and the `SimplifiedActivity` has had some changes in the meantime. This tries to take the ideas from that PR and implement them in the current, up-to-date codebase.
Changes:
- Add `TextView`s to *activity_simplified.xml* to display the identity name
- Add code to *SimplifiedActivity.java* to show/hide the current identity name
- Fix typo in mDbHelper: `getIdentitys()` -> `getIdentities()`

Feature: Show identity name in SimplifiedActivity

---

app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/processors/SQRLStorage.java

Issue #314 
Description:
Enable import of base64-url encoded identities as per https://www.grc.com/sqrl/storage.htm
> Although S4 is nominally a binary representation, it may be necessary to convey the file over a binary-hostile medium. In this case the standard eight-byte signature will be converted to all uppercase 'SQRLDATA' and the balance of the database will be encoded into 6-bit base64url format for representation, storage or transmission over a binary-intolerant channel.
> When a SQRL client encounters a database beginning with uppercase 'SQRLDATA' it must immediately lowercase the 8-byte header and pass the balance of the database through a base64url decoder to restore the database to binary. Processing may then proceed normally.
To aid in the exchange of SQRL data during …

Enable import of base64-url encoded identities

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/MainActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportOptionsActivity.java
app/src/main/res/layout/activity_import_options.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml

Issue #314.
Description:
Enable importing a sqrl identity file from within the app. Also, consolidate the import UI.
Changes:
- Implement `Intent.ACTION_GET_CONTENT` to pick an identity file for import
- Add `ImportOptionsActivity` which now hosts all currently available import-options:
- Scan identity qr code
- Import identity file
- Import with text input

File import feature and import UI consolidation

---

app/src/main/java/org/ea/sqrl/activites/StartActivity.java

Issue #322 .
Description:
Fix a regression where importing an identity via qr code scan initiated from the `StartActivity` would fail due to a missing intent extra.
Changes:
- Add `EXTRA_IMPORT_METHOD` to the intent with the value `IMPORT_METHOD_QRCODE`

Bugfix: QR code import not working in StartActivity

---

app/src/androidTest/java/org/ea/sqrl/AccessibilityInstrumentedTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/SimplifiedActivity.java
app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java
app/src/main/java/org/ea/sqrl/activites/create/NewIdentityDoneActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/IdentityManagementActivity.java
app/src/main/res/layout/activity_identity_management.xml
app/src/main/res/menu/menu_default.xml
app/src/main/res/values/strings.xml

Issue #317.
Description:
First steps in the discussed refactoring of `MainActivity`.
Changes:
- Rename `MainActivity` to `IdentityManagementActivity`
- Rename `Advanced operations` to `Identity management`
- Remove `Use identity`
- Reorder buttons on `IdentityManagementActivity` so that corresponding items are closer to each other
This is "part 1" of the changes for this issue, which mainly deals with stuff under the hood. As soon as we've discussed the settings issue and how exactly the consolidation of the buttons should look like, I'll come in with "part 2".

Improve MainActivity

---

app/src/main/java/org/ea/sqrl/activites/base/LoginBaseActivity.java

Issue #325 
Description:
Removed the login popup after a failed login attempt.
Changes:
If the user types the wrong password, they will see the error message.  Once they dismiss the error message, the login popup will show as the next action.

remove login popup after failed password

---

app/src/main/res/layout-land/activity_url_login.xml
app/src/main/res/layout-land/fragment_login.xml
app/src/main/res/layout/activity_url_login.xml
app/src/main/res/layout/fragment_login.xml

Issue #331 
Description:
Make the domain name on the login screen(s) bigger and monospace.
Changes:
- Change `TextView` to `android.support.v7.widget.AppCompatTextView`
- Add `app:autoSizeTextType="uniform"` and other properties to the text view to enable dynamic text sizing

Improve domain verification

---

app/src/main/res/values-night/colors.xml

Description:
Look at a Google IO talk about Material design suggesting using 700 and 200 for the colors of different layouts to have good contrasts
Changes:
Use the same color for primaryColor and primaryColorDark so the status bar has the same color as our appbar. Also changed the accentColor to use two new purple colors with the right contrast difference.
What do you think about the new colors? @alexhauser @sengsational @sesam

Better contrasting colors for night and day mode.

---

app/src/main/java/org/ea/sqrl/activites/SettingsActivity.java

Issue #329.
Fixes the "Missing argument" error that was encountered when logging in using biometrics after identity settings have been saved. 
The reason for the error was that upon saving the identity, QuickPass state is lost. However, a subsequent call to `storage.hasQuickPass()` woud still return `true` due to a missing call to `storage.clearQuickPass()`.
**Changes:**
- Added a call to `storage.clearQuickPass()` upon saving identity settings.
While this fixes the error at hand, we should still think about a better overall solution, where saving settings can leverage an existing active QuickPass (allow biometric auth instead of full password) and also engage QuickPass on successful password input.

Fix "Missing argument" error on biometric login

---

app/src/main/java/org/ea/sqrl/activites/identity/RenameActivity.java
app/src/main/res/layout/activity_rename.xml

Description:
Just a few small improvements that make renaming identities quicker and less painful.
Changes:
- Focus the text field, select all text and pop up keyboard so that one can immediately start typing a new name
- Add `android:imeOptions="actionDone"` and some code to start the renaming when the Enter/Done button is pressed on the soft keyboard.

Improve ux in RenameActivity

---

app/src/main/AndroidManifest.xml

Issue #355.
Exclude UrlLoginActivity from history and recent apps, so that it is not possible to switch back to a "stale" login window using "recent apps".

Exclude login activity from history and recent apps

---

app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ResetPasswordActivity.java
app/src/main/res/values/strings.xml

Issue #348.
Description:
When the `ResetPasswordActivity` is called from an import job, change the activity title, descriptive text and button text to better reflect that we are "setting a new password" in this case instead of "resetting the password".
Changes:
- Added some strings that better describe what's going on when the `ResetPasswordActivity` was called from an import job
- Added a check if the `ResetPasswordActivity` was called from an import job (by checking if the Intent Extra `SQRLStorage.NEW_IDENTITY` is set to `true`). If it was, the new texts are applied.
Fixes:
- Empty import activity would linger after successful import of an identity without password
- Intent Extra `SQRLStorage.NEW_IDENTITY` was missing when importing an identity without password

Improve reset password on import

---

app/src/main/java/org/ea/sqrl/activites/SimplifiedActivity.java
app/src/main/java/org/ea/sqrl/activites/StartActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportOptionsActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java

Issue #369.
Description:
Handle scanning an identity qr-code on the main screen scan button by "forwarding" the qr-code data to the `ImportActivity`.
Changes:
- Add new import method named `IMPORT_METHOD_FORWARDED_QR_CODE` as intent extra for `ImportActivity`; Also, I've moved all the static strings used for intent extras from `ImportOptionsActivity` to `ImportActivity`
- Detect the type of qr-code in `SimplifiedActivity` and forward data to `ImportActivity` if an identity qr-code was detected, adding the above import method extra to the intent
- Handle a forwarded identity qr-code in `ImportActivity` if present in the intent extras
I also noticed that we were still using the `readSQRLQRCodeAsString(Intent data)`, which did not iterate over the qr-code byte segments, but instead would …

Handle scanning an identity qr-code from the main screen

---

app/src/main/java/org/ea/sqrl/processors/CommunicationFlowHandler.java
app/src/main/java/org/ea/sqrl/processors/CommunicationHandler.java
app/src/main/java/org/ea/sqrl/processors/SQRLStorage.java

Description:
When you rekey an identity this identity will have an old previous key and then the new key is put into our secret vault. This means that you will have new suk (server unlock key) and vuk (verify unlock key). These must be communicated with the server when a previous key has been found to be valid.
Changes:
Set a boolean in Storage when a previous key has been found.
Send suk and vuk when previous key is sent to the server.

Fixing rekey function.

---

app/src/main/res/drawable/ic_announcement_accent_24dp.xml
app/src/main/res/layout/activity_cps_missing.xml

Improve the layout of `CPSMissingActivity`.
This is how the activity looks before the proposed changes:
... and here with the changes applied:

Improve layout of CPSMissingActivity

---

app/src/main/res/drawable/ic_assignment_turned_in_accent_24dp.xml
app/src/main/res/layout/activity_new_identity_done.xml

Improve the layout of `NewIdentityDoneActivity`.
This is how the activity looks before the proposed changes:
... and here with the changes applied:

Improve layout of NewIdentityDoneActivity

---

app/src/main/java/org/ea/sqrl/utils/SqrlApplication.java
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout/activity_login.xml

Revised fix to https://github.com/alexhauser/secure-quick-reliable-login/pull/1
Fix crash bug related to srcCompat on old APIs.
Changes:
- Remove `android:src` and change `tools:srcCompat` to `app:srcCompat` on ImageViews in `LoginActivity`
- Add `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` to onCreate of our Application class to correctly initialize the vector drawables support library

Fix crash bug related to srcCompat on old APIs

---

app/src/main/res/drawable/ic_identity_management_accent_24dp.xml
app/src/main/res/layout/activity_identity_management.xml

Issue #401
Improve the UX of `IdentityManagementActivity`
Changes:
- Add a hero icon to the top of the page in substitution for the redundant headline
- Change the button text for creating a new identity from "*CREATE NEW*" to "*CREATE IDENTITY*". (No new string needed, we already had that one!)
I left the floating action button design behind for now, since this would have needed a little more discussion I guess. Maybe we can look at this again at a later stage.

Improve id management

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-he/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-no/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-zh/strings.xml
app/src/main/res/values/strings.xml

Issue #406
*Description:*
Fix the string name for the title of `EnableQuickPassActivity` as discussed in the above issue.
*Changes:*
- Change string name from `quickpass_enable_heading` to `title_enable_quickpass` for all languages. (@kalaspuffar , will you please handle this in POEditor? Thanks!)
- While working in the manifest, I found that there are still left-overs of deleted activities. I removed those.

Fix "Enable QuickPass" title

---

app/src/main/java/org/ea/sqrl/activites/create/SaveIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/RenameActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ResetPasswordActivity.java
app/src/main/java/org/ea/sqrl/database/IdentityDBHelper.java
app/src/main/res/values/strings.xml

Issue #405
Change the default naming of identities as discussed in the above issue. (*"My Identity"*, *"My Identity 2"* ...)
**Changes:**
- Add translatable string for the default identity name (*"My Identity"*)
- Update `IdentityDBHelper.updateIdentityName()` to use the new default name if an empty string or `null` is provided for the `name` argument
- Add a call to `updateIdentityName()` within `IdentityDBHelper.newIdentity()` to ensure that every identity has a default name associated upon creation. Until now, it was possible to have identities without names
**Further discussion:**
I will post a new issue to discuss how we could simplify naming upon creating a new identity.
//EDIT: Here we go: https://github.com/kalaspuffar/secure-quick-reliable-login/issues/414

Improve naming of identities

---

app/src/main/res/layout/activity_introduction.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

In night mode, the text color of the selected tab header in `IntroductionActivity` had a very low contrast (black on dark gray):
Changing it to `colorAccent` only for night mode looks mutch better:

Fix intro tab color in night mode

---

app/src/main/java/org/ea/sqrl/activites/create/SaveIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/RenameActivity.java
app/src/main/java/org/ea/sqrl/utils/SqrlApplication.java
app/src/main/res/layout/activity_save_identity.xml

Issue #414.
When creating a new identity, don't ask for an identity name if it's the first identity. 
(In essence, duplicate the behaviour that we use on import)
**Changes:**
- Remove identity name field from `SaveIdentityActivity`
- Upon identity creation, if it is not the first identity, send the user to the `RenameActivity` after saving the identity. Using an intent extra, let `RenameActivity` know that it should launch `NewIdentityDoneActivity` after the renaming process instead of `MainActivity`.

Simplify naming when creating a new identity

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/MainActivity.java
app/src/main/java/org/ea/sqrl/activites/StartActivity.java
app/src/main/java/org/ea/sqrl/activites/base/CommonBaseActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/IdentityManagementActivity.java

**Issue #419**
Configure `CommonBaseActivity` to have the back navigation in the action bar
**Changes:**
Changed settings for action bar.  Added implementation to call `onBackPressed()` when navigation activated.  Removed `parentActivityName` from identity management manifest item.
**Discussion:**
There's more ways to get this same result than the way this PR does it, but if this does what we want, it's pretty simple.  It seems that if various activities customized `onBackPressed()`, then this solution should honor those customizations (although I'm posting this without very much testing to validate those).  There were no other instances of `parentActivityName` associated with activities in the manifest, but that would also be an alternative way to approach this.
In cases …

back arrow on common base

---

app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java

***Issue #421***
***Description:***
Display options menu on `MainActivity` only.
***Changes:***
Altered visibility of `action_identity_management` options menu item to be gone from everywhere except the main  `MainActivity`
***Discussion:***
Almost all of the activities that extend `BaseActivity` (where the options menu is defined) are "downstream" in activity flow of `IdentityManagementActivity`, so don't have the need to navigate to identity management this way.  There might be a few non-downstream activities, such as `LoginBaseActivity` and `StartActivity` that, before this change had the ability to navigate to identity management, but it didn't seem to make sense to add those (but we could).

Selective display of identity management in options menu

---

app/src/main/java/org/ea/sqrl/activites/create/CreateIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/create/EntropyGatherActivity.java
app/src/main/java/org/ea/sqrl/activites/create/NewIdentityDoneActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeEnterActivity.java
app/src/main/java/org/ea/sqrl/activites/create/RescueCodeShowActivity.java
app/src/main/java/org/ea/sqrl/activites/create/SaveIdentityActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/RenameActivity.java

Enable going back one step at a time in identity creation wizard. 
This enables going back to double check the rescue code if the user notices in the next step that it was recorded incorrectly. The rescue code input will always start with a blank form though, to avoid a situation where the user would go back and forth to input the rescue code without recording it.
**Changes:**
- Don't immediately finish activities which are part of the "create identity" wizard. Finish all activities upon saving the identity though.
- Move `showPhoneStatePermission()` from `onCreate()` to `onResume()` in `EntropyGatherActivity` to also start gathering entropy when resuming the activity
- Fix the "back" behaviour of `RenameActivity` and `NewIdentitiyDoneActivity` so that the new …

Enable "one step back" in identity creation wizard

---

app/src/main/res/layout-land/activity_show_identity.xml
app/src/main/res/layout/activity_show_identity.xml

Issue #427.
Fix the layout of the textual identity representation in `ShowIdentityActivity`.
**Changes:**
- Change with and height attributes of `txtIdentityText` from `0dp` to `wrap_content` in both landscape and portrait, so that the textual identity will display centered horizontally as well as vertically (while keeping the text left-aligned)
- Added dummy text to help design time visualization

Fix identity show layout

---

app/src/main/res/drawable/alt_id_input_background.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Issue #432.
This PR aims at fixing the issue of the Alt-Id input textfield not being recognizable or being mistaken for a headline for the radio button group below.
**Changes:**
Added a background color around the Alt-Id input text field and info icon to make it stand out as an input control.
This is how it looks now, I hope you all agree that this should solve the problem without overly bloating the layout:
(sorry for the German screenshots)
And in dark mode:

Fix Alt-Id input field not recognizable

---

app/src/main/java/org/ea/sqrl/services/IdentityPrintDocumentAdapter.java
app/src/main/java/org/ea/sqrl/services/RescueCodePrintDocumentAdapter.java
app/src/main/java/org/ea/sqrl/utils/Utils.java
app/src/main/res/values/strings.xml

Issue #438.
Improve the layout and UX of the page that is being created when a user prints the rescue code during the creation of a new identity.
This basically duplicates the layout and texts from GRC's reference client and adds an additional app-specific footer.
**Changes:**
- Add headline, warning and descriptive texts
- Add footer (logo and app info)
- Break drawing the footer layout out into a utility function `Utils.drawPrintPageFooter(...)` so that it can be reused by by all `PrintDocumentAdapter`s
- Add utility function `Utils.drawTextBlock(...)` to draw (multiline) text onto the canvas
**Discussion:**
@kalaspuffar, I noticed that in `IdentityPrintDocumentAdapter` you created a custom text-wrapping functionality for drawing multi-line text blocks. My new utility …

Improve rescue code printout page

---

app/src/main/java/org/ea/sqrl/services/IdentityPrintDocumentAdapter.java
app/src/main/java/org/ea/sqrl/services/RescueCodePrintDocumentAdapter.java
app/src/main/java/org/ea/sqrl/utils/DocumentPrintUtils.java
app/src/main/java/org/ea/sqrl/utils/Utils.java

Followup to issue #439.
This is the discussed followup-PR that ports the improvements of the rescue code printout to the identity printout.
**Changes:**
- Move utility functions to a dedicated class called `DocumentPrintUtils`
- Port `IdentityPrintDocumentAdapter` to the new `drawTextBlock(...)` utility function
- Remove legacy code for drawing multiline text blocks, including helper functions

PrintDocumentAdapter improvements

---

app/src/main/java/org/ea/sqrl/utils/EncryptionUtils.java

In `EncryptionUtils.xor()`, we iterate over two byte arrays, using the length of the first array as the abort condition. Since the second byte array may be shorter, this creates a potential for an `ArrayIndexOutOfBoundsException`.
**Changes:**
Apply a modulo operation on the second array's indexer so that it will wrap around to 0 if the second array is shorter than the first one.

Fix potential "index out of bounds" in EncryptionUtils.xor()

---

app/src/main/java/org/ea/sqrl/utils/EncryptionUtils.java

Issue #452.
Fix a regression where the number of hash iterations within `EncryptionUtils.enHash()` was increased by one, causing the function to produce incorrect results.
Increasing the iteration count from 15 to 16 within the for-loop was unnecessary, since the first iteration is already done outside the loop.

Fix EnHash regression

---

app/src/main/java/org/ea/sqrl/utils/EncryptionUtils.java

Issue #449.
Add missing zero-padding in `EncryptionUtils.decodeBase56()`.
This should make the new base56 unit tests pass.
**Notes:**
Changing `EncryptionUtils.reverse()` to public just mirrors the changes in PR #450 to avoid merge conflicts.

Fix zero-padding in base56 decode

---

app/src/test/java/org/ea/sqrl/EnHashUnitTest.java
app/src/test/java/org/ea/sqrl/TestHelper.java

Issue #448.
Add unit test for EnHash vectors.
**Note:**
Adding the base64 helpers to the `TestHelper` class was necessary because we use the Android base64 implementation which is not available in the local unit tests.

Add EnHash unit test

---

app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java

Issue #461.
This fixes an integer overflow bug in `BaseActivity.clearQuickPassAfterTimeout()` which could cause negative _QuickPass Timeout_ values, effectively disabling QuickPass when large timeout values were used.

Fix QuickPass Timeout bug

---

app/src/main/java/org/ea/sqrl/activites/MainActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java

Issue #467 .
**Description:** 
This fixes the "_App crashes on non-SQRL QC codes_" bug which was reported in the forums at https://sqrl.grc.com/threads/problem-with-dummy-qr-code.1097/.
**Changes:**
- Added validity check for the scanned qr code data using the new utility function `Utils.isValidSqrlUri()`.
- Changed error messages from popup messages to toast messages, since the error popups seemed too arcane and invasive for such a mundane error condition.

Fix "App crashes on non-SQRL QC codes"

---

app/src/main/java/org/ea/sqrl/activites/identity/ChangePasswordActivity.java
app/src/main/res/layout/activity_change_password.xml

Closes issue #476 
Enable the "show password" toggle on all password fields within `ChangePasswordActivity` to enable un-masking entered passwords. This should make it easier for users to get their password entries right.
**Changes:**
- Replace all `EditText` instances with `TextInputLayout` and set `app:passwordToggleEnabled="true"` on them
- Clear QuickPass on successful password change, since leaving it active would cause the next QuickPass-enabled login to fail.
- Some small optimizations in error situations (e.g. don't just blindly empty all password fields, but only those that actually caused the error)

Enable "show password" on ChangePasswordActivity

---

app/src/main/java/org/ea/sqrl/activites/LoginActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/IdentitySettingsActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ResetPasswordActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java
app/src/main/res/layout/activity_reset_password.xml
app/src/main/res/layout/fragment_save_settings.xml

Fixes issue #474.
This PR will re-mask passwords upon form submission in case the user has chosen to display them in plain text while entering. 
This was implemented for the following activities:
- `LoginActivity`
- `IdentitySettingsActivity`
- `ResetPasswordActivity`
**Notes**:
Once PR #478 is merged, we should probably backport this to `ChangePasswordActivity` as well.
Also, while I was working at the layout files, I've added a few small autofill optimizations along the way to start addressing issue #475.

Re-mask passwords when submitting

---

app/src/main/java/org/ea/sqrl/activites/identity/ChangePasswordActivity.java

Completes fix for issue #474, follow-up to PR #479.
**Description**:
Backport the re-masking of passwords upon form submission to `ChangePasswordActivity` .

Re-mask password in ChangePasswordActivity

---

app/src/main/java/org/ea/sqrl/activites/identity/IdentityManagementActivity.java

Issue https://github.com/kalaspuffar/secure-quick-reliable-login/issues/487
Description:
Forces a reload of the identity data on resume of identity management after create identity
Changes:
Loads the current identity ID from context and does a full reload of the identity data through the SqrlApplication class

Reload identity onResume

---

app/src/main/java/org/ea/sqrl/activites/MainActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/java/org/ea/sqrl/utils/QRCodeDecodeHelper.java
app/src/main/java/org/ea/sqrl/utils/QRCodeDecodedBitStreamParser.java

Issue #481.
Description:
This PR will try to solve the issue with an incorrect reading of QR Codes. It did not read the QRCode correctly because the QRCode could be encoded in multiple different ways to compress as well as possible.
* Numeric
* Alpha Numeric
* Byte stream
* Kanji
* Hanzi
As a URL seldom has Kanji or Hanzi data, I've not addressed these because I don't really understand the encoding.
For byte streams, it's pretty straightforward. They read them and add them to a list. They also add that data to a string value. Numeric or alphanumeric encoding was only added to the string value.
Changes:
My solution adds the byte stream list to the numeric and alphanumeric functions and handles the reading of these encoded values adding them to a byte stream of its own. This will, in turn, …

Added QR decoder
