app/src/main/java/org/ea/sqrl/processors/CommunicationFlowHandler.java

Issue #266.
Description:
The program will re-ask the same question over and over when you try the ask function at
https://www.grc.com/sqrl/ask.htm
Changes:
Added a line to clear the last response before running the next query to the server.

Clear response before asking.

---

app/src/main/java/org/ea/sqrl/activites/SimplifiedActivity.java
app/src/main/res/drawable/ic_scan_qr_black_24dp.xml
app/src/main/res/layout/activity_simplified.xml

Issue #252  Improve login experience
Description:
Created an icon and associated button on mail activity.'
Changes:
Added `<Button...` which uses a new vector graphic icon of a magnifying glass aiming at a simplified QR code.
Notes:
This change was as much for training me how to use the source control that's integrated with Android Studio as anything.  I have no doubt that there's some "real" UI people out there that will give us guidelines, but we could use this in the mean time.

Add scan qr icon and associated button

---

app/src/main/java/org/ea/sqrl/activites/CPSMissingActivity.java
app/src/main/java/org/ea/sqrl/processors/CommunicationFlowHandler.java
app/src/main/java/org/ea/sqrl/processors/CommunicationHandler.java
app/src/main/java/org/ea/sqrl/processors/SQRLStorage.java

Issue #297.
Description:
Changing the alternative id function to work similarly to the reference client.
Changes:
Added a null character between the domain+ext data and the alternative id in order to follow the specification.

Added null character in text for alternative ID.

---

app/src/main/java/org/ea/sqrl/activites/UrlLoginActivity.java
app/src/main/java/org/ea/sqrl/activites/account/AccountOptionsActivity.java

Issue #301.
Description:
The application should return to the website when you use the alternative ID function.
Changes:
Added calls to close all the extra views when entering the optional features of the login window.

Return to webpage when you use alternative id function.

---

app/src/main/java/org/ea/sqrl/activites/UrlLoginActivity.java
app/src/main/java/org/ea/sqrl/activites/base/LoginBaseActivity.java

Issue #296.
Description:
Check if the dropdown value has changed and update quickpass prompt.

Handle update of the login field when changing identity in dropdown.

---

app/build.gradle
app/src/main/res/layout/password_strength_meter.xml
app/src/main/res/values/colors.xml

Issue #306.
Description:
Strength meter font was unreadable in dark mode.
Changes:
Set fixed font color for strength meter components.

Fix strength meter dark mode and display issues

---

app/src/main/java/org/ea/sqrl/activites/StartActivity.java
app/src/main/res/layout-land/activity_start.xml
app/src/main/res/layout/activity_start.xml
app/src/main/res/values/strings.xml

Issue #339.
Description:
The feature for imorting an identity from a file was missing in the `StartActivity`. 
Changes:
- Removed the buttons for `Scan identity QR code` and `Import with text input` from StartActivity and replaced them with one button `Import identity`
- Wired up the new button to start the `ImportOptionsActivity`

Add file import to StartActivity

---

app/src/main/AndroidManifest.xml

Issue #351.
Description:
Temporarily remove `android.intent.action.VIEW` file intent filter until Google provides a better solution for filtering for file extensions.

Remove file intent

---

app/src/main/java/org/ea/sqrl/activites/base/BaseActivity.java
app/src/main/res/menu/menu_default.xml

Issue #373.
Description:
Remove "Identity management" menu item on IdentityManagementActivity

Remove "Identity management" menu item on IdentityManagementActivity

---

app/src/main/res/layout-land/activity_show_identity.xml
app/src/main/res/layout/activity_show_identity.xml

Issue #380 
Add white background around QR code for night-mode scanning.
**Changes:**
Added background to portrait and landscape QR code layouts.

display QR code with white background

---

app/src/main/java/org/ea/sqrl/activites/identity/RenameActivity.java

Issue #396
Improve program flow on "import with recovery" by launching the main activity after the "rename" step.

Improve program flow on "import with recovery"

---

app/src/main/java/org/ea/sqrl/activites/identity/ImportActivity.java
app/src/main/res/drawable/ic_import_accent_24dp.xml
app/src/main/res/layout-land/activity_import.xml
app/src/main/res/layout/activity_import.xml
app/src/main/res/layout/activity_import_options.xml

Small import improvements
**Changes:**
- On `ImportActivity`, start the import when hitting "Done" on the soft keyboard after entering the identity password instead of only focussing the "Import" button
- Center-align the text box for the textual identity in `ImportActivity`
- Add hero icon to `ImportOptionsActivity`

Improve import

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/ea/sqrl/activites/identity/IdentityManagementActivity.java
app/src/main/java/org/ea/sqrl/activites/identity/ImportOptionsActivity.java
app/src/main/java/org/ea/sqrl/utils/Utils.java
app/src/main/res/drawable/identity_selector_layout_border.xml
app/src/main/res/layout/activity_identity_management.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_identity_selector.xml

Fixes for a bunch of small problems I've noticed along the way.
**Changes:**
- Replace our custom "back" button in `IdentityManagementActivity` with a stock back action on the action bar (which made the next change below much easier because the custom back image is not "in the way" anymore)
- Hide hero icon in IdentityManagementActivity on small resolutions (helps a lot in landscape)
- Hide hero icon in ImportOptionsActivity on small resolutions (helps a lot in landscape)
- Fix "black background" bug on IdentitySelector on old APIs
- Fix focus issues in LoginActivity and IdentitySelector

Miscellaneous fixes

---

app/src/main/java/org/ea/sqrl/utils/IdentitySelector.java

Improve the confirmation message which is shown upon identity removal.
**Changes:**
- Add the identity name and an icon to the message dialog

Improve identity removal

---

app/src/main/java/org/ea/sqrl/activites/create/EntropyGatherActivity.java

Issue #436.
This is an attempt at fixing the _"Camera is being used after Camera.release() was called"_ issue. It's hard to debug such a problem if you don't have the device on which the error occurs, but I'll give it a try anyway.
This incorporates a few suggestions from https://stackoverflow.com/questions/13235306/method-called-after-release-exception-camera-preview
**Changes:**
- Call `removeView(mPreview)` on the preview layout to avoid it holding a reference to the "old" camera object after it was being released
- Move all deinitialization/release code from the "next button"-handler to `onPause()`, so that it is reliably being called in any situation that causes the activity to pause
- Move setting the preview callback from `CameraPreview::surfaceChanged()` to …

Fix camera use after release bug

---

app/src/main/java/org/ea/sqrl/processors/SQRLStorage.java

Description:
Fixing the rescue code generation.
Changes:
Added a description and changed to use a 32-byte random source.

Fixing the rescue code creation.

---

app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-he/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-id/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-no/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-zh/strings.xml
app/src/main/res/values/strings.xml

Changes:
Updated language strings in preparation for release.

Updated language strings.

---

CHANGELOG
app/build.gradle
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-he/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-id/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-no/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values-zh/strings.xml
app/src/main/res/values/strings.xml

Changes:
Release branch with CHANGELOG and build number. 
This will be the base for release if approved.

Release v1.6.0

---

CHANGELOG

Changes:
Forgot to mention new languages in changelog.

Forgot to mention new languages in changelog.

---

CHANGELOG
app/build.gradle

* Enable "show password" option when changing password
* Re-mask passwords when submitting
* Compiled for newer Android versions.

Release 1.7.1
